### ISSUE TITLE
TypeError: __randomstate_ctor() takes from 0 to 1 positional arguments but 2 were given

### ISSUE THREAD

**Issue by chengchengxinyi** [btjaden/TargetRNA3#2]
Hello,
I encountered an error when trying to run TargetRNA3.

$ python TargetRNA3.py -s SgrS.fa -g Genomes/GCF_000005845.2
Traceback (most recent call last):
  File "TargetRNA3.py", line 480, in <module>
    df_output, mRNA_info, sRNA_conservation = run_TargetRNA3(sRNA_name, sRNA_sequence)
  File "TargetRNA3.py", line 465, in run_TargetRNA3
    y_pred_proba = predictions(X)
  File "TargetRNA3.py", line 374, in predictions
    model_info = pickle.load(in_file)
TypeError: __randomstate_ctor() takes from 0 to 1 positional arguments but 2 were given

I previously used the Python 3.10 that comes with the Ubuntu system. Later, I tried to install Python 3.7.1 to install an older version of numpy, version 1.17.3. The error still persisted. How can I resolve this?

**Comment by chengchengxinyi** [comment]
Thank you very much, the issue has been resolved. 
The error is likely caused by version mismatch. By executing the test code mentioned by the owner in another issue, I modified the versions of scikit-learn, numpy, and scipy. TargetRNA3 can run smoothly.

**Comment by chengchengxinyi** [comment]
Thank you very much, the issue has been resolved.
The error is likely caused by version mismatch. By executing the test code mentioned by the owner in another issue, I modified the versions of scikit-learn, numpy, and scipy. TargetRNA3 can run smoothly.
